'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const base=path.join(__dirname,'..');
const context={window:{}};vm.createContext(context);
for(const file of ['library.js',...fs.readdirSync(path.join(base,'core')).filter(f=>f.endsWith('.js')&&f!=='library.js').sort()])vm.runInContext(fs.readFileSync(path.join(base,'core',file),'utf8'),context,{filename:file});
const core=context.window.PREP_CORE;
const section=id=>Object.values(core).flatMap(t=>t.learn).find(s=>s.id===id);
const activity=id=>Object.values(core).flatMap(t=>t.activities).find(a=>a.id===id);
assert.match(section('lie-f7').body,/min\(1,p\(x\)\/q\(x\)\)/);
assert.match(section('lie-f7').body,/positive residual/);
assert.match(section('lie-f3').body,/may still return or stream/);
const kvCheck=section('lie-f2').check;
assert.match(kvCheck.question,/actually retains 8,000 tokens instead of 4,000/);
assert.match(kvCheck.question,/full-attention.*dynamically allocated/);
assert.match(kvCheck.question,/unchanged KV heads, layers, element precision and no eviction/);
assert.equal(kvCheck.answer,1);
assert.match(kvCheck.options[kvCheck.answer],/actual retained token count/);
assert.match(kvCheck.explain,/configured maximum context does not necessarily double occupied KV bytes/);
assert.match(kvCheck.explain,/preallocation.*allocator\/metadata overhead/);
const flashCheck=section('lie-f5').check;
assert.equal(flashCheck.answer,1);
assert.match(flashCheck.explain,/tiles and running normalization\/output statistics/);
assert.match(flashCheck.explain,/avoiding materialization of the full attention matrix/);
assert.match(flashCheck.explain,/full matrix does not stay in SRAM/);
assert.match(flashCheck.explain,/declared tolerances/);
const inferenceRows=core['llm-inference-engineering'].glossary.flatMap(g=>g.rows);
assert.match(inferenceRows.find(r=>r[0]==='Prefill')[1],/often compute-heavy.*depending on workload/);
assert.match(inferenceRows.find(r=>r[0]==='Decode')[1],/often bandwidth-heavy.*depending on workload/);
assert.match(section('qbllm-1').body,/which workload or implementation changes could alter the bottleneck/);
assert.match(section('qbllm-1').body,/model-specific prices affect latency and cost/);
assert.match(section('tas-0').body,/scheduled groups such as warps/);
assert.doesNotMatch(section('tas-0').body,/all run the same instruction/);
assert.match(section('raa-0').body,/learned sparse models also exist/);
assert.match(section('raa-0').check.options[section('raa-0').check.answer],/learned sparse models also exist/);
assert.match(section('tas-f7').check.options[section('tas-f7').check.answer],/mathematically equivalent.*declared tolerances/);
assert.match(section('tas-f7').check.explain,/does not imply bitwise identity/);
assert.match(section('raa-f8').check.question,/100 requests.*80 requests.*remaining 20/);
assert.match(section('raa-f8').check.explain,/first attempt the small model/);
assert.equal(100-(80*0.10+20*1),72);
assert.equal(100*0.10+20*1,30);
assert.match(section('lft-f4').body,/not norm-bounded/);
assert.match(section('lft-f4').deeper,/Position resets alone/);
assert.match(activity('tas-a2').rubric,/Accept FSDP alone/);
assert.match(activity('raa-a3').rubric,/actual send-time arguments/);
assert.match(section('raa-f5').check.options[section('raa-f5').check.answer],/1\/3/);
assert.match(section('lie-f0').body,/algorithm plus vocabulary/);
assert.match(section('lie-f0').body,/SentencePiece supports Unigram and BPE/);
assert.match(section('gp-f1').deeper,/quadratic sequence term/);
assert.match(section('gp-f1').deeper,/not make latency universally linear/);
assert.match(section('gp-0').check.explain,/not proof that cache always bounds concurrency/);
assert.match(section('qbllm-4').deeper,/rather than occurring instantly/);
assert.match(section('qbllm-1').deeper,/Greedy reproducibility assumes identical logits\/runtime/);
assert.match(section('qbllm-3').deeper,/fixed multipliers are illustrative assumptions/);
assert.match(activity('raa-a3').model,/does not rule out every exfiltration route/);
const inferenceViz=fs.readFileSync(path.join(__dirname,'viz','llm-inference.js'),'utf8');
assert.match(inferenceViz,/hs = \[18, 36, 54, 72, 90, 108\]/);
assert.match(inferenceViz,/policy-dependent~admission pressure/);
assert.match(inferenceViz,/Aggregate time per output token summarizes/);
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures','ai-diagnostics.json')));
for(const r of fixture.requests)assert.equal(r.ttft_ms,r.queue_ms+r.prefill_ms+r.upstream_ms);
for(const shape of fixture.lora)assert.equal(shape.parameters,shape.rank*(shape.input+shape.output));
const m=fixture.memory;assert.equal((m.parameter_bytes+m.gradient_bytes+m.optimizer_master_bytes/m.ranks)*m.parameters,7e9);
assert.equal((m.parameter_bytes+(m.gradient_bytes+m.optimizer_master_bytes)/m.ranks)*m.parameters,5.5e9);
assert.equal((m.parameter_bytes+m.gradient_bytes+m.optimizer_master_bytes)*m.parameters/m.ranks,4e9);
const residual=fixture.speculative.p.map((p,i)=>Math.max(0,p-fixture.speculative.q[i]));const sum=residual.reduce((a,b)=>a+b,0);
assert.deepEqual(residual.map(x=>x/sum),fixture.speculative.normalized_positive_residual);
// Reconstruct p from accepted draft mass plus rejection residual, testing the actual displayed formula.
const acceptance=fixture.speculative.p.map((p,i)=>Math.min(1,p/fixture.speculative.q[i]));
const reject=1-fixture.speculative.q.reduce((s,q,i)=>s+q*acceptance[i],0);
fixture.speculative.p.forEach((p,i)=>assert.ok(Math.abs(p-(fixture.speculative.q[i]*acceptance[i]+reject*residual[i]/sum))<1e-12));
// A reset position index alone still permits cross-example causal attention.
assert.equal(fixture.batch.position_ids[4],0);
assert.notEqual(fixture.batch.example_ids[3],fixture.batch.example_ids[4]);
assert.equal(fixture.batch.loss_mask[5],0);assert.ok(fixture.batch.tokens.some(t=>fixture.batch.held_out_ids.includes(t)));
console.log('AI effective-content, trace, memory, adapter-shape, batch and speculative-distribution regressions passed');

assert.doesNotMatch(section('lie-0').body,/dominated by the memory-bound decode step/);
assert.match(section('lie-0').body,/small-batch decode is often bandwidth-heavy, depending on workload/);
