'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const base=path.join(__dirname,'..');
const context={window:{}};vm.createContext(context);
for(const file of ['library.js',...fs.readdirSync(path.join(base,'core')).filter(f=>f.endsWith('.js')&&f!=='library.js').sort()])vm.runInContext(fs.readFileSync(path.join(base,'core',file),'utf8'),context,{filename:file});
const core=context.window.PREP_CORE;
const section=id=>Object.values(core).flatMap(t=>t.learn).find(s=>s.id===id);
const activity=id=>Object.values(core).flatMap(t=>t.activities).find(a=>a.id===id);
assert.match(section('lie-f7').body,/min\(1,p\(x\)\/q\(x\)\)/);
assert.match(section('lie-f7').body,/positive residual/);
assert.match(section('lie-f3').body,/may still return or stream/);
assert.match(section('lft-f4').body,/not norm-bounded/);
assert.match(section('lft-f4').deeper,/Position resets alone/);
assert.match(activity('tas-a2').rubric,/Accept FSDP alone/);
assert.match(activity('raa-a3').rubric,/actual send-time arguments/);
assert.match(section('raa-f5').check.options[section('raa-f5').check.answer],/1\/3/);
assert.match(section('lie-f0').body,/algorithm plus vocabulary/);
assert.match(section('lie-f0').body,/SentencePiece supports Unigram and BPE/);
assert.match(section('gp-f1').deeper,/quadratic sequence term/);
assert.match(section('gp-f1').deeper,/not make latency universally linear/);
assert.match(section('gp-0').check.explain,/not proof that cache always bounds concurrency/);
assert.match(section('qbllm-4').deeper,/rather than occurring instantly/);
assert.match(section('qbllm-1').deeper,/Greedy reproducibility assumes identical logits\/runtime/);
assert.match(section('qbllm-3').deeper,/fixed multipliers are illustrative assumptions/);
assert.match(activity('raa-a3').model,/does not rule out every exfiltration route/);
const inferenceViz=fs.readFileSync(path.join(__dirname,'viz','llm-inference.js'),'utf8');
assert.match(inferenceViz,/hs = \[18, 36, 54, 72, 90, 108\]/);
assert.match(inferenceViz,/policy-dependent~admission pressure/);
assert.match(inferenceViz,/Aggregate time per output token summarizes/);
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures','ai-diagnostics.json')));
for(const r of fixture.requests)assert.equal(r.ttft_ms,r.queue_ms+r.prefill_ms+r.upstream_ms);
for(const shape of fixture.lora)assert.equal(shape.parameters,shape.rank*(shape.input+shape.output));
const m=fixture.memory;assert.equal((m.parameter_bytes+m.gradient_bytes+m.optimizer_master_bytes/m.ranks)*m.parameters,7e9);
assert.equal((m.parameter_bytes+(m.gradient_bytes+m.optimizer_master_bytes)/m.ranks)*m.parameters,5.5e9);
assert.equal((m.parameter_bytes+m.gradient_bytes+m.optimizer_master_bytes)*m.parameters/m.ranks,4e9);
const residual=fixture.speculative.p.map((p,i)=>Math.max(0,p-fixture.speculative.q[i]));const sum=residual.reduce((a,b)=>a+b,0);
assert.deepEqual(residual.map(x=>x/sum),fixture.speculative.normalized_positive_residual);
// Reconstruct p from accepted draft mass plus rejection residual, testing the actual displayed formula.
const acceptance=fixture.speculative.p.map((p,i)=>Math.min(1,p/fixture.speculative.q[i]));
const reject=1-fixture.speculative.q.reduce((s,q,i)=>s+q*acceptance[i],0);
fixture.speculative.p.forEach((p,i)=>assert.ok(Math.abs(p-(fixture.speculative.q[i]*acceptance[i]+reject*residual[i]/sum))<1e-12));
// A reset position index alone still permits cross-example causal attention.
assert.equal(fixture.batch.position_ids[4],0);
assert.notEqual(fixture.batch.example_ids[3],fixture.batch.example_ids[4]);
assert.equal(fixture.batch.loss_mask[5],0);assert.ok(fixture.batch.tokens.some(t=>fixture.batch.held_out_ids.includes(t)));
console.log('AI effective-content, trace, memory, adapter-shape, batch and speculative-distribution regressions passed');
